// Publishes the built site (dist/) to the gh-pages branch — the branch
// GitHub Pages serves. Run via:  npm run deploy
// Safe to re-run: dist/ is regenerated by the build and its history is
// recreated each time, then force-pushed (gh-pages holds only built files).
import { spawnSync } from 'node:child_process';
import { existsSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const DIST = join(ROOT, 'dist');
// Repo URL comes from this clone's `origin` remote — works for any repo.
const remote = spawnSync('git', ['remote', 'get-url', 'origin'], { cwd: ROOT, encoding: 'utf8' });
const REPO = remote.status === 0 ? remote.stdout.trim() : '';
if (!REPO) {
  console.error('✗ Could not read the "origin" git remote — is this a clone of your GitHub repo?');
  process.exit(1);
}

function git(args, cwd) {
  const r = spawnSync('git', args, { cwd, stdio: 'inherit' });
  if (r.status !== 0) {
    console.error(`\n✗ git ${args.join(' ')} failed`);
    process.exit(1);
  }
}

if (!existsSync(join(DIST, 'index.html'))) {
  console.error('✗ dist/index.html is missing — run `npm run build` first (or use `npm run deploy`).');
  process.exit(1);
}

// Fresh repo each run: vite empties dist/ on every build.
rmSync(join(DIST, '.git'), { recursive: true, force: true });
// Skip Jekyll processing on GitHub Pages so all assets are served as-is.
writeFileSync(join(DIST, '.nojekyll'), '');

git(['init', '-b', 'gh-pages'], DIST);
git(['remote', 'add', 'origin', REPO], DIST);
git(['add', '-A'], DIST);
git(['-c', 'user.name=mwithablog7', '-c', 'user.email=mwithablog7@users.noreply.github.com', 'commit', '-m', 'Deploy portfolio build'], DIST);
git(['push', '--force', 'origin', 'HEAD:gh-pages'], DIST);

const pages = REPO.match(/github\.com[:/]([^/]+)\/([^/.]+)/);
const pagesUrl = pages ? `https://${pages[1].toLowerCase()}.github.io/${pages[2]}/` : '(GitHub Pages URL)';
console.log(`\n✓ Deployed dist/ → gh-pages. Live in ~1 min: ${pagesUrl}`);
